# Generated by Django 3.1.3 on 2020-12-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0007_auto_20201208_1839'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saved_programs',
            field=models.ManyToManyField(blank=True, to='universities.StudyProgramInUniversity'),
        ),
        migrations.AddField(
            model_name='user',
            name='search_university_history',
            field=models.ManyToManyField(blank=True, to='universities.University'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscribe',
            field=models.BooleanField(default=False),
        ),
    ]
