# Generated by Django 3.1.3 on 2020-11-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_auto_20201125_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyprogram',
            name='degree',
            field=models.CharField(blank=True, choices=[('bachelor', 'Bachelor'), ('master', 'Master')], max_length=10, null=True),
        ),
    ]
