# Generated by Django 3.1.3 on 2020-12-08 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_studyprogram_degree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='studyprogram',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='studyprogram',
            name='duration_in_month',
        ),
        migrations.RemoveField(
            model_name='studyprogram',
            name='form_of_study',
        ),
        migrations.RemoveField(
            model_name='studyprogram',
            name='price',
        ),
        migrations.RemoveField(
            model_name='studyprogram',
            name='scholarship_availability',
        ),
        migrations.RemoveField(
            model_name='studyprogram',
            name='scholarship_description',
        ),
        migrations.RemoveField(
            model_name='studyprogram',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='university',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='university',
            name='study_programs',
        ),
        migrations.AddField(
            model_name='country',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='studyprogram',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='StudyProgramInUniversity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('scholarship_availability', models.BooleanField(default=False)),
                ('scholarship_description', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration_in_month', models.IntegerField(blank=True, null=True)),
                ('form_of_study', models.CharField(blank=True, choices=[('OFFLINE', 'Offline'), ('ONLINE', 'Online')], max_length=10, null=True)),
                ('degree', models.CharField(blank=True, choices=[('bachelor', 'Bachelor'), ('master', 'Master')], max_length=10, null=True)),
                ('start_of_study', models.CharField(blank=True, max_length=255, null=True)),
                ('study_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_study_programs', to='universities.studyprogram')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_study_programs', to='universities.university')),
            ],
        ),
    ]
