# Generated by Django 3.1.3 on 2020-12-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0004_auto_20201208_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyprograminuniversity',
            name='currency',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
