# Generated by Django 3.1.3 on 2020-12-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0005_studyprograminuniversity_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyprograminuniversity',
            name='duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
