# Generated by Django 3.1.3 on 2020-12-08 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0006_studyprograminuniversity_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='studyprogram',
            options={'verbose_name': 'Study Program', 'verbose_name_plural': 'Study Programs'},
        ),
        migrations.AlterModelOptions(
            name='studyprograminuniversity',
            options={'verbose_name': 'University Study Program', 'verbose_name_plural': 'University Study Programs'},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name': 'University', 'verbose_name_plural': 'Universities'},
        ),
    ]
