# Generated by Django 3.1.3 on 2020-12-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0008_auto_20201208_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='img_url',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
