# Generated by Django 3.1.3 on 2020-12-09 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0009_auto_20201208_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.CharField(blank=True, max_length=255, null=True)),
                ('end_date', models.CharField(blank=True, max_length=255, null=True)),
                ('deadline', models.CharField(blank=True, max_length=255, null=True)),
                ('money_amount', models.CharField(blank=True, max_length=255, null=True)),
                ('conditions_for_participation', models.TextField(blank=True, null=True)),
                ('list_of_documents', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Grant',
                'verbose_name_plural': 'Grants',
            },
        ),
    ]
