#!/bin/bash
set -e

POSTGRES="psql --username ${POSTGRES_USER}"

echo "Creating database role: ${DB_USER}"

$POSTGRES <<-EOSQL
CREATE USER ${DB_USER} WITH CREATEDB LOGIN ENCRYPTED PASSWORD '${DB_PASS}';
ALTER USER ${DB_USER} WITH SUPERUSER;
EOSQL
